### ISSUE TITLE
no TCP Sink block

### ISSUE THREAD

**Issue by mnjagadeesh** [ha7ilm/rpitx-app-note#6]
Hi,
I was trying these samples. I am using Gnu Radio Companion 3.8.0. I do not find TCP Sink block.
Is there anyway to install it?

**Comment by ha7ilm** [comment]
My notes might be outdated, they're definitely not corresponding to the latest `gnuradio` and `rpitx`. The `TCP Sink` block might have been renamed. I suggest that you search for just `TCP` in GRC. I think it's a quite a standard thing, so there should be a corresponding block. 

Otherwise this is more a GNU Radio related question, so you can use their wiki/mailing list/chat rooms to seek for an answer.
